- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1109/INFOCOM42981.2021.9488705
  title: An Incentive Mechanism for Cross-Silo Federated Learning: A Public Goods Perspective

- id: doi:10.1109/JIOT.2022.3218948
  title: Improving Information Freshness via Backbone-Assisted Cooperative Access Points
  
- id: doi:10.1109/TMC.2020.3038710
  title: Online Bitrate Selection for Viewport Adaptive 360-Degree Video Streaming

- id: doi:10.1109/TMC.2020.3036871
  title: Deep Reinforcement Learning for Task Offloading in Mobile Edge Computing Systems

- id: doi:10.1109/TNET.2021.3071488
  title: How Do You Earn Money on Live Streaming Platforms? A Study of Donation-Based Markets

- id: doi:10.1109/MCOM.001.1900354
  title: Communication, Computation, and Caching Resource Sharing for Internet-of-Things

- id: doi:10.1109/JSAC.2018.2874123
  title: Enabling Edge Cooperation in Tactile Internet via 3C Resource Sharing

- id: doi:10.1109/TNET.2018.2859236
  title: Multi-Dimensional Auction Mechanisms for Crowdsourced Mobile Video Streaming

- id: doi:10.1109/TMC.2018.2834358
  title: Multi-User Cooperative Mobile Video Streaming: Performance Analysis and Online Mechanism Design

- id: doi:10.1109/MCOM.2017.1600830
  title: Optimizations and Economics of Crowdsourced Mobile Streaming

- id: doi:10.48550/arXiv.2307.14346
  title: Multi-objective Deep Reinforcement Learning for Mobile Edge Computing

- id: doi:10.1109/INFOCOM42981.2021.9488705
  title: An Incentive Mechanism for Cross-Silo Federated Learning: A Public Goods Perspective

- id: doi:10.1109/INFOCOM.2019.8737362
  title: How to Earn Money in Live Streaming Platforms?—A Study of Donation-Based Markets

- id: doi:10.1109/INFOCOM.2017.8057025
  title: MOMD: A Multi-Object Multi-Dimensional Auction for Crowdsourced Mobile Video Streaming

 



