- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1109/INFOCOM42981.2021.9488705


- id: doi:10.1109/JIOT.2022.3218948

  
- id: doi:10.1109/TMC.2020.3038710

- id: doi:10.1109/TMC.2020.3036871

- id: doi:10.1109/TNET.2021.3071488

- id: doi:10.1109/MCOM.001.1900354

- id: doi:10.1109/JSAC.2018.2874123

- id: doi:10.1109/TNET.2018.2859236

- id: doi:10.1109/TMC.2018.2834358

- id: doi:10.1109/MCOM.2017.1600830

- id: doi:10.48550/arXiv.2307.14346

- id: doi:10.1109/INFOCOM42981.2021.9488705

- id: doi:10.1109/INFOCOM.2019.8737362

- id: doi:10.1109/INFOCOM.2017.8057025

 



